#!/usr/bin/env python3
"""Rebuilds a maintained target from the 26.1.2 root: its source tree and its debug companion.

    python tools/port/port_version.py 26.2            # tree and companion
    python tools/port/port_version.py 1.21.11 --tree  # only versions/kohs-inventory-tweaks-1.21.11
    python tools/port/port_version.py all

Features are written once, in the root tree. Every other target is the root with its
version's API differences applied, and those differences live here, each one checked
against that version's client jar. After a port, build the target and run
`python tools/verify-all-versions.py`; a mixin whose target moved again shows up
there before the game ever starts.

The rebuild replaces `src/client` and `src/main` of the target. Files a target needs
that the root cannot produce (its replacement for a mixin whose target moved) are
listed in `KEEP` and carried across. Anything else edited by hand in a target is
lost, which is the point: the root is the only place to edit.

The debug companions follow the 26.1.2 companion. Its labs stay in tools/qa; 26.1
and 26.1.1 compile them from there, while 26.2 and 1.21.11 get a translated copy
under `src/qa`, regenerated by this script.
"""
from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
PKG = "src/client/java/dev/zymekoh/kohsinventorytweaks"
DEBUG_PKG = "src/client/java/dev/zymekoh/kohsinventorydebug"
LABS = ("cursor-contract", "pvp-input", "showcase")
TARGETS = ("26.1", "26.1.1", "26.2", "1.21.11")

# Files only the target itself can provide, relative to its package root: mixins
# whose target moved, and the key order read from that version's own jar.
KEEP = {
    "26.2": ("mixin/GuiScreenMixin.java", "mixin/HudMixin.java", "inventory/VanillaKeyOrder.java"),
    "1.21.11": ("mixin/WindowMixin.java", "inventory/VanillaKeyOrder.java"),
}
DEBUG_KEEP = {"26.2": ("GuiTraceMixin.java",)}


def read(path: Path) -> tuple[str, bool]:
    raw = path.read_bytes().decode("utf-8")
    return raw.replace("\r\n", "\n"), "\r\n" in raw


def write(path: Path, text: str, crlf: bool) -> None:
    path.write_bytes((text.replace("\n", "\r\n") if crlf else text).encode("utf-8"))


def edit(path: Path, pairs) -> None:
    """Exact replacements that must each match once, so a moved line fails loudly."""
    text, crlf = read(path)
    for old, new in pairs:
        if text.count(old) != 1:
            raise SystemExit(f"{path.relative_to(REPO)}: expected one match for {old[:80]!r}, found {text.count(old)}")
        text = text.replace(old, new)
    write(path, text, crlf)


def remove_member(path: Path, start_marker: str) -> None:
    """Removes one annotated member, from its annotation to its closing brace."""
    text, crlf = read(path)
    start = text.index(start_marker)
    end = text.index("\n\t}\n", start) + len("\n\t}\n")
    head, tail = text[:start], text[end:].lstrip("\n")
    if tail.startswith("}"):
        # It was the last member: no blank line before the class closes.
        head = head.rstrip("\n") + "\n"
    write(path, head + tail, crlf)


def sources(*roots_and_kept) -> list[Path]:
    """Every Java file under the given roots, except the target's own kept files."""
    *roots, kept = roots_and_kept
    return [path for root in roots for path in root.rglob("*.java") if path.name not in kept]


def camel(name: str) -> str:
    head, *rest = name.lower().split("_")
    return head + "".join(part.capitalize() for part in rest)


def apply_rules(files, rules) -> int:
    changed = 0
    for java in files:
        text, crlf = read(java)
        new = text
        for pattern, replacement in rules:
            new = pattern.sub(replacement, new)
        if new != text:
            changed += 1
            write(java, new, crlf)
    return changed


# 26.2 moved screen ownership from Minecraft to Gui and the HUD to Hud. The owner must
# not follow a dot, or package names such as Fabric's client.screen.v1 would match.
OWNER = r"(?<![\w.])(minecraft|this\.minecraft|mc|client|Minecraft\.getInstance\(\))"
RULES_26_2 = [
    (re.compile(OWNER + r"\.setScreen\("), r"\1.gui.setScreen("),
    (re.compile(OWNER + r"\.screen\b(?!\()"), r"\1.gui.screen()"),
    (re.compile(OWNER + r"\.getOverlay\(\)"), r"\1.gui.overlay()"),
    (re.compile(OWNER + r"\.getToastManager\(\)"), r"\1.gui.toastManager()"),
    (re.compile(OWNER + r"\.gui\.getChat\(\)"), r"\1.gui.hud.getChat()"),
    (re.compile(OWNER + r"\.getMainRenderTarget\(\)"), r"\1.gameRenderer.mainRenderTarget()"),
    (re.compile(OWNER + r"\.isSingleplayer\(\)"), r"\1.hasSingleplayerServer()"),
    (re.compile(r"\.getMainCamera\(\)"), ".mainCamera()"),
    # The HUD's hidden flag moved from Options to Hud, behind a toggle.
    (re.compile(r"(\w+)\.options\.hideGui = (\w+);"), r"if (\1.gui.hud.isHidden() != \2) \1.gui.hud.toggle();"),
    (re.compile(r"(\w+)\.options\.hideGui\b"), r"\1.gui.hud.isHidden()"),
    # Entity type constants moved to EntityTypes; EntityType keeps the class itself.
    (re.compile(r"\bEntityType\.([A-Z][A-Z0-9_]+)\b"), r"EntityTypes.\1"),
    (re.compile(r"^import net\.minecraft\.world\.entity\.EntityType;$", re.M),
     "import net.minecraft.world.entity.EntityType;\nimport net.minecraft.world.entity.EntityTypes;"),
    # Coloured items became ColorCollections: Items.PURPLE_DYE is Items.DYE.purple().
    (re.compile(r"\bItems\.([A-Z_]+?)_(DYE|SHULKER_BOX)\b"),
     lambda m: f"Items.{'DYE' if m.group(2) == 'DYE' else 'DYED_SHULKER_BOX'}.{camel(m.group(1))}()"),
]

# 1.21.11 is the last render-era version: GuiGraphics and render*/draw* names.
RENAMES_1_21_11 = {
    "GuiGraphicsExtractor": "GuiGraphics",
    "extractRenderStateWithTooltipAndSubtitles": "renderWithTooltipAndSubtitles",
    "extractRenderState": "render",
    "extractBackground": "renderBackground",
    "extractSlotHighlightBack": "renderSlotHighlightBack",
    "extractSlot": "renderSlot",
    "extractWidgetRenderState": "renderWidget",
    "extractEntityInInventoryFollowsMouse": "renderEntityInInventoryFollowsMouse",
    "extractContents": "renderContents",
    "extractTransparentBackground": "renderTransparentBackground",
    "extractSnapbackItem": "renderSnapbackItem",
    "extractTooltip": "renderTooltip",
    "extractScrollingStringOverContents": "renderScrollingStringOverContents",
    "extractItemHotbar": "renderItemHotbar",
    "LightCoordsUtil": "LightTexture",
    "ContainerInput": "ClickType",
    "afterExtract": "afterRender",
}
DRAW_CALLS_1_21_11 = {
    "text": "drawString",
    "centeredText": "drawCenteredString",
    "textWithWordWrap": "drawWordWrap",
    "outline": "renderOutline",
    "item": "renderItem",
    "itemDecorations": "renderItemDecorations",
    "entity": "submitEntityRenderState",
}
RULES_1_21_11 = [(re.compile(rf"\b{old}\b"), new) for old, new in RENAMES_1_21_11.items()]
RULES_1_21_11 += [(re.compile(rf"\bgraphics\.{old}\("), f"graphics.{new}(") for old, new in DRAW_CALLS_1_21_11.items()]
RULES_1_21_11 += [
    (re.compile(r"import net\.minecraft\.util\.LightTexture;"), "import net.minecraft.client.renderer.LightTexture;"),
    (re.compile(r"net/minecraft/client/renderer/state/gui/pip/"), "net/minecraft/client/gui/render/state/pip/"),
    (re.compile(r"net\.minecraft\.client\.renderer\.state\.gui\.pip\."), "net.minecraft.client.gui.render.state.pip."),
    (re.compile(r"\.containerInput\(\)"), ".clickType()"),
    (re.compile(r"\.resizeGui\(\)"), ".resizeDisplay()"),
]


def port_tree(version: str) -> None:
    target = REPO / f"versions/kohs-inventory-tweaks-{version}"
    mixins = target / PKG / "mixin"
    kept = {name: (target / PKG / name).read_bytes() for name in KEEP.get(version, ())}
    for part in ("src/client", "src/main"):
        shutil.rmtree(target / part)
        shutil.copytree(REPO / part, target / part)
    for name, data in kept.items():
        (target / PKG / name).write_bytes(data)
    kept = {Path(name).name for name in kept}
    edit(target / "src/main/resources/fabric.mod.json", [('"minecraft": "26.1.2"', f'"minecraft": "{version}"')])
    mixin_config = target / "src/main/resources/kohs_inventory_tweaks.client.mixins.json"

    if version == "26.2":
        # Verified against the 26.2 client jar: Minecraft#setScreen moved to Gui, the
        # HUD from Gui to Hud, AbstractContainerScreen lost its snapback extraction,
        # and the picture-in-picture states changed constructor types (no sign state).
        (mixins / "MinecraftScreenMixin.java").unlink()
        (mixins / "GuiMixin.java").unlink()
        edit(mixin_config, [
            ('    "MinecraftScreenMixin",\n', '    "GuiScreenMixin",\n'),
            ('    "GuiMixin",\n', '    "HudMixin",\n'),
        ])
        container = mixins / "AbstractContainerScreenMixin.java"
        remove_member(container, '\t@Inject(method = "extractSnapbackItem"')
        edit(container, [
            ("import dev.zymekoh.kohsinventorytweaks.render.InventoryAnimationController;\n", ""),
            ("@Mixin(AbstractContainerScreen.class)\n",
             "/** 26.2 has no snapback extraction, so there is no item-return motion to reduce here. */\n"
             "@Mixin(AbstractContainerScreen.class)\n"),
        ])
        scene = mixins / "ContainerSceneMixin.java"
        edit(scene, [
            ("GuiSkinRenderState;<init>(Lnet/minecraft/client/model/player/PlayerModel;",
             "GuiSkinRenderState;<init>(Lnet/minecraft/client/model/Model$Simple;"),
            ("GuiEntityRenderState;<init>(Lnet/minecraft/client/renderer/entity/state/EntityRenderState;Lorg/joml/Vector3f;Lorg/joml/Quaternionf;Lorg/joml/Quaternionf;",
             "GuiEntityRenderState;<init>(Lnet/minecraft/client/renderer/entity/state/EntityRenderState;Lorg/joml/Vector3fc;Lorg/joml/Quaternionfc;Lorg/joml/Quaternionfc;"),
        ])
        remove_member(scene, '\t@ModifyArgs(method = "sign"')
        changed = apply_rules(sources(target / PKG, kept), RULES_26_2)
    elif version == "1.21.11":
        # Verified against the 1.21.11 client jar and Fabric API 0.141.6. The complete
        # GLFW poll ends in Window#updateDisplay (Minecraft#run has no pollEvents), there
        # is no Window#isFocused or Camera#getFov, handleKeybinds drains no HUD toggle
        # before the inventory, the container background is drawn in renderBg, and the
        # picture-in-picture states live in gui.render.state.pip, built by GuiGraphics'
        # submit*RenderState.
        (mixins / "MinecraftInputPollMixin.java").unlink()
        edit(mixin_config, [
            ('"compatibilityLevel": "JAVA_25"', '"compatibilityLevel": "JAVA_21"'),
            ('    "MinecraftInputPollMixin",\n', '    "WindowMixin",\n'),
        ])
        edit(target / "src/main/resources/fabric.mod.json", [('"java": ">=25"', '"java": ">=21"')])
        edit(target / PKG / "inventory/SuperFastInventoryController.java", [
            ("!minecraft.isWindowActive() || !minecraft.getWindow().isFocused() || ", "!minecraft.isWindowActive() || "),
        ])
        edit(target / PKG / "cursor/CursorLandingController.java", [
            ("\n\t\t\t&& minecraft.getWindow().isFocused() && !minecraft.getWindow().isMinimized();",
             "\n\t\t\t&& !minecraft.getWindow().isMinimized();"),
        ])
        edit(target / PKG / "KoHsInventoryTweaksClient.java", [
            (".registerReloadListener(", ".registerReloader("),
            ("import net.fabricmc.fabric.api.client.rendering.v1.LivingEntityRenderLayerRegistrationCallback;",
             "import net.fabricmc.fabric.api.client.rendering.v1.LivingEntityFeatureRendererRegistrationCallback;"),
            ("LivingEntityRenderLayerRegistrationCallback.EVENT", "LivingEntityFeatureRendererRegistrationCallback.EVENT"),
        ])
        edit(target / PKG / "input/ConfigMenuKeyBinding.java", [
            ("import net.fabricmc.fabric.api.client.keymapping.v1.KeyMappingHelper;",
             "import net.fabricmc.fabric.api.client.keybinding.v1.KeyBindingHelper;"),
            ("KeyMappingHelper.registerKeyMapping(", "KeyBindingHelper.registerKeyBinding("),
        ])
        for name in ("render/VisiblePlayerBackdropController.java", "render/VisiblePlayerGlowController.java"):
            edit(target / PKG / name, [
                ("Math.max(20.0F, camera.getFov())", "Math.max(20.0, minecraft.options.fov().get())"),
            ])
        edit(mixins / "ContainerSceneMixin.java", [
            ('@ModifyArgs(method = "skin"', '@ModifyArgs(method = "submitSkinRenderState"'),
            ('@ModifyArgs(method = "entity"', '@ModifyArgs(method = "submitEntityRenderState"'),
            ('@ModifyArgs(method = "book"', '@ModifyArgs(method = "submitBookModelRenderState"'),
            ('@ModifyArgs(method = "bannerPattern"', '@ModifyArgs(method = "submitBannerPatternRenderState"'),
            ('@ModifyArgs(method = "sign"', '@ModifyArgs(method = "submitSignRenderState"'),
        ])
        edit(mixins / "ContainerScreenMixin.java", [('method = "extractBackground",', 'method = "renderBg",')])
        edit(mixins / "InventoryScreenMixin.java", [
            ('method = "extractBackground(Lnet/minecraft/client/gui/GuiGraphicsExtractor;IIF)V",', 'method = "renderBg",'),
        ])
        edit(target / PKG / "compat/CompatibilityIssueManager.java", [
            ('"net.minecraft.client.gui.screens.inventory.InventoryScreen#extractBackground -> "',
             '"net.minecraft.client.gui.screens.inventory.InventoryScreen#renderBg -> "'),
        ])
        changed = apply_rules(sources(target / PKG, kept), RULES_1_21_11)
    else:
        changed = 0
    print(f"tree {version}: rebuilt from 26.1.2, {changed} files translated")


def port_debug(version: str) -> None:
    source = REPO / "debug/kohs-inventory-debug-26.1.2"
    target = REPO / f"debug/kohs-inventory-debug-{version}"
    mixins = target / DEBUG_PKG / "mixin"
    kept = {name: (mixins / name).read_bytes() for name in DEBUG_KEEP.get(version, ())}
    for part in ("src/client", "src/main"):
        shutil.rmtree(target / part)
        shutil.copytree(source / part, target / part)
    for name, data in kept.items():
        (mixins / name).write_bytes(data)
    if version in ("26.1", "26.1.1"):
        print(f"debug {version}: rebuilt from the 26.1.2 companion; labs compile from tools/qa")
        return

    qa = target / "src/qa"
    if qa.exists():
        shutil.rmtree(qa)
    for lab in LABS:
        (qa / lab).mkdir(parents=True)
        for java in (REPO / "tools/qa" / lab).glob("*.java"):
            shutil.copy(java, qa / lab / java.name)
    java_files = [path for path in list((target / "src/client/java").rglob("*.java")) + list(qa.rglob("*.java"))
                  if path.name not in kept]
    config = target / "src/client/resources/kohs-inventory-debug.client.mixins.json"

    if version == "26.2":
        # Screen ownership moved to Gui: the lifecycle hooks follow it into GuiTraceMixin.
        remove_member(mixins / "MinecraftTraceMixin.java", '\t@Inject(method = "setScreen", at = @At("HEAD"))')
        remove_member(mixins / "MinecraftTraceMixin.java", '\t@Inject(method = "setScreen", at = @At("RETURN"))')
        edit(mixins / "MinecraftTraceMixin.java", [
            ("import net.minecraft.client.gui.screens.Screen;\n", ""),
            ("import org.jspecify.annotations.Nullable;\n", ""),
        ])
        trace, crlf = read(mixins / "GuiTraceMixin.java")
        if "RecordingOverlay.opened()" not in trace:
            edit(mixins / "GuiTraceMixin.java", [
                ("\t\tDebugCollector.onSetScreen(Minecraft.getInstance(), screen, true);\n",
                 "\t\tDebugCollector.onSetScreen(Minecraft.getInstance(), screen, true);\n"
                 "\t\tif (screen instanceof net.minecraft.client.gui.screens.inventory.InventoryScreen) {\n"
                 "\t\t\tdev.zymekoh.kohsinventorydebug.RecordingOverlay.opened();\n"
                 "\t\t}\n"),
            ])
        edit(config, [('    "InventoryScreenInitProbeMixin",\n', '    "GuiTraceMixin",\n    "InventoryScreenInitProbeMixin",\n')])
        changed = apply_rules(java_files, RULES_26_2)
    else:
        edit(config, [('"compatibilityLevel": "JAVA_25"', '"compatibilityLevel": "JAVA_21"')])
        edit(target / "src/main/resources/fabric.mod.json", [('"java": ">=25"', '"java": ">=21"')])
        edit(target / DEBUG_PKG / "MacroTestController.java", [
            ("!minecraft.isWindowActive() || !minecraft.getWindow().isFocused() || ", "!minecraft.isWindowActive() || "),
        ])
        # 1.21.11 LevelSettings: (name, mode, hardcore, difficulty, commands, rules, data).
        edit(target / DEBUG_PKG / "LabWorld.java", [
            ("\t\t\t\tLevelSettings.DifficultySettings.DEFAULT,\n\t\t\t\ttrue,\n\t\t\t\tWorldDataConfiguration.DEFAULT\n",
             "\t\t\t\tfalse,\n\t\t\t\tnet.minecraft.world.Difficulty.NORMAL,\n\t\t\t\ttrue,\n"
             "\t\t\t\tnew net.minecraft.world.level.gamerules.GameRules(WorldDataConfiguration.DEFAULT.enabledFeatures()),\n"
             "\t\t\t\tWorldDataConfiguration.DEFAULT\n"),
        ])
        changed = apply_rules(java_files, RULES_1_21_11)
    print(f"debug {version}: rebuilt from the 26.1.2 companion, {changed} files translated (labs in src/qa)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("version", choices=(*TARGETS, "all"))
    parser.add_argument("--tree", action="store_true", help="only the source tree")
    parser.add_argument("--debug", action="store_true", help="only the debug companion")
    arguments = parser.parse_args()
    both = not arguments.tree and not arguments.debug
    for version in TARGETS if arguments.version == "all" else (arguments.version,):
        if both or arguments.tree:
            port_tree(version)
        if both or arguments.debug:
            port_debug(version)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
