#!/usr/bin/env python3
"""Bakes the Zymekoh skin into ui/MascotSkin.java, the pixels the mascot is drawn from.

    python tools/mascot/gen_mascot_skin.py

The source is the Zymekoh player skin (64x64, slim arms), stored next to this
script. Each region is kept as its own layer -- face and hood, body and jacket --
so the mascot can move the pixels of each layer on their own. Pixel data instead
of a texture keeps the mascot identical on every Minecraft version: nothing about
it depends on how a version loads images.
"""
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
OUT = REPO / "src/client/java/dev/zymekoh/kohsinventorytweaks/ui/MascotSkin.java"

# name: (x, y, width, height) in the standard 64x64 skin layout.
REGIONS = {
    "HEAD": (8, 8, 8, 8),          # face, base layer
    "HOOD": (40, 8, 8, 8),         # hood, outer layer
    "BODY": (20, 20, 8, 12),       # body front, base layer
    "BACK": (32, 20, 8, 12),       # body back: the tail is painted here
    "ARM": (44, 20, 3, 12),        # slim right arm, front
    "LEG": (4, 20, 4, 12),         # right leg, front
}


def argb(pixel):
    r, g, b, a = pixel
    return 0 if a == 0 else (a << 24) | (r << 16) | (g << 8) | b


def main() -> None:
    skin = Image.open(HERE / "zymekoh_skin.png").convert("RGBA")
    lines = [
        "package dev.zymekoh.kohsinventorytweaks.ui;",
        "",
        "/**",
        " * The Zymekoh skin, region by region, as ARGB pixels in rows (0 is transparent).",
        " * Generated by tools/mascot/gen_mascot_skin.py from tools/mascot/zymekoh_skin.png;",
        " * edit the skin and run the script rather than this file.",
        " */",
        "final class MascotSkin {",
    ]
    for name, (x0, y0, width, height) in REGIONS.items():
        values = [argb(skin.getpixel((x, y))) for y in range(y0, y0 + height) for x in range(x0, x0 + width)]
        lines.append(f"\tstatic final int {name}_WIDTH = {width};")
        lines.append(f"\tstatic final int[] {name} = {{")
        for row in range(height):
            chunk = values[row * width:(row + 1) * width]
            lines.append("\t\t" + ", ".join(f"0x{v:08X}" for v in chunk) + ",")
        lines.append("\t};")
        lines.append("")
    lines += [
        "\tprivate MascotSkin() {",
        "\t}",
        "}",
        "",
    ]
    OUT.write_bytes("\r\n".join(lines).encode("utf-8"))
    print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
